apiVersion: spec.keptn.sh/0.1.4
kind: Remediation
metadata:
  name: carts-remediation
spec:
  remediations:
    - problemType: Response time degradation
      actionsOnOpen:
        - action: trigger-servicenow-flow
          name: Trigger ServiceNow Flow
          description: Creates an Incident
          value:
            flowApiPath: /api/dynat/keptn_create_incident # mandatory parameter
            httpMethod: POST # mandatory parameter
            retries: 10
    - problemType: Failure rate increase
      actionsOnOpen:
        - action: toggle-feature
          name: Toogle feature flag
          description: Toogle feature flag EnablePromotion to OFF
          value: 
            EnablePromotion: "off"
